/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Lambda": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Topic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
  }
}
